repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua

  # - repo: https://github.com/Koihik/luacheck
  #   rev: v1.1.2
  #   hooks:
  #     - id: luacheck
  #       args: [--globals, vim]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
