name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
      - uses: leafo/gh-actions-luarocks@v4
      - name: Install luacheck
        run: luarocks install luacheck
      - name: Run luacheck
        run: luacheck lua/ --globals vim

  stylua:
    name: StyLua
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/ plugin/

  tests:
    name: Run tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        neovim_version: ['v0.9.0', 'v0.10.0', 'nightly']
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        uses: rhymond/setup-nvim@v1
        with:
          version: ${{ matrix.neovim_version }}
      - name: Install dependencies
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter
      - name: Run tests
        run: |
          nvim --version
          make test

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [luacheck, stylua, tests]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@v1
        if: contains(github.event.head_commit.message, 'chore(release)')
        with:
          tag: ${{ github.event.head_commit.message | sed 's/.*v\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/v\1/' }}
          message: Release ${{ github.event.head_commit.message | sed 's/.*v\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/v\1/' }}
